source: remove deno for the time being
as it does not support raspi 4

```
error: snap "deno" is not available on stable for this architecture (arm64) but exists on other
       architectures (amd64).
```